version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rentops_production
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: mysql2://root:root@db:3306/rentops_production
      REDIS_URL: redis://redis:6379/1
      JWT_SECRET_KEY: rentops_docker_production_jwt_secret_key_2026
    depends_on:
      - db
      - redis

volumes:
  db_data:
